### ISSUE TITLE
Slides are not sorted alphabetically by ContainerIdentifier in left handle panel

### ISSUE THREAD

**Issue by dclunie** [herrmannlab/slim#108]
Appear to be in random order, where as alpha sort would be useful.

E.g., "https://slim-idc-htan-dot-idc-external-006.uc.r.appspot.com/studies/2.25.38649134330414220812979591492650088495/series/1.3.6.1.4.1.5962.99.1.847609172.1004632042.1650115083604.3.0"

**Comment by hackermd** [comment]
We currently sort by Series Number. We could readily change that and sort by Container Identifier instead.

**Comment by dclunie** [comment]
Series Number is always 1 for our images, so Container Identifier would be better (or Series Number then Container Number).

**Comment by hackermd** [comment]
> Series Number is always 1 for our images, so Container Identifier would be better (or Series Number then Container Number).

Why is Series Number always 1? Shouldn't every digital slide correspond to one or more series, each having a unique Series Number?

**Comment by dclunie** [comment]
Ideally, but I didn't implement it in the conversion scripts and hadn't noticed it until you mentioned it.

**Comment by hackermd** [comment]
I have personally found it difficult to assign values to Series Number reliably, especially for derived information, because they may be generated in parallel by independent systems. It's unclear to me what unique guarantees the standard provides for values of Series Number (if any?). We should probably avoid relying on Series Number in the viewer. Since it's a type 2 attribute, we may even want to omit the value altogether upon conversion.
