### ISSUE TITLE
Green dot left after GoTo

### ISSUE THREAD

**Issue by waynewccheng** [herrmannlab/slim#125]
A green dot was left behind after using the Go-To feature

**Comment by hackermd** [comment]
Thanks for your feedback @waynewccheng. Could you kindly elaborate a bit on the issue that you are experiencing?

The go-to tool is expected to create a "ROI" with graphic type POINT.

Here is an example from our public demo at https://herrmannlab.github.io/slim:

<img width="1512" alt="Screen Shot 2022-09-09 at 5 24 04 PM" src="https://user-images.githubusercontent.com/6855297/189447992-4c1e4b66-7601-438b-b7a0-63d1097cd58e.png">

If that's the "dot" you are referring to, then that's expected behavior.

**Comment by waynewccheng** [comment]
Thanks for the explanation. I didn't know that the POINT is intended. I thought the go-to tool was a numerical pan, and the POINT would disappear for taking a clean screenshot of the ROI.

**Comment by hackermd** [comment]
We've been using the go-to tool also to focus on specific anatomical or morphological structures. If a structure is small (e.g., an individual cell) it may be difficult to identify without a marker. In addition, the go-to tool can be used as an annotation tool to mark structures and potentially later revisit or save the coordinates.

If that behavior is surprising or annoying, we could make the drawing of the marker optional. We are very open to ideas or suggestions for improvement.
