### ISSUE TITLE
Color mismatch between slide view and overview view

### ISSUE THREAD

**Issue by fedorov** [herrmannlab/slim#95]
This is for an HTAN sample. Overview is yellow, slide is green.

studies/2.25.56219147941526607962658668060030231728/series/1.3.6.1.4.1.5962.99.1.848706586.916152681.1650116181018.3.0

<img width="697" alt="image" src="https://user-images.githubusercontent.com/313942/165958260-22e0622d-768f-4a38-affe-62ec8ab69fb9.png">

**Comment by hackermd** [comment]
That is a most interesting sample. I can't reproduce the issue with the different colors in the main viewport and the overview viewport. What browser are you using?

However, I discovered a few other interesting details about these images.

According to the metadata this digital slide represents a collection of monochromatic images with three unique optical paths (i.e., three "channels").

The image metadata looks as follows:
 - Samples per pixel: 1
 - Photometric Interpretation: MONOCHROME2

@dclunie is it possible that these are actually color images that should have Photometric Interpretation `RGB` instead of `MONOCHROME2` (background value for all three channels is 255 rather than 0) and Samples per Pixels `3` instead of `1`?

![Screen Shot 2022-05-12 at 1 54 59 PM](https://user-images.githubusercontent.com/6855297/168139275-1a5b1c42-83bf-449f-8985-b78054044697.png)

![Screen Shot 2022-05-12 at 1 55 20 PM](https://user-images.githubusercontent.com/6855297/168139286-3fd61e45-1a2b-47ce-beb3-86a9a662f449.png)

![Screen Shot 2022-05-12 at 1 59 09 PM](https://user-images.githubusercontent.com/6855297/168139294-57469956-7c11-48c5-9506-92cc4f9d2e57.png)

**Comment by dclunie** [comment]
If these are HTAN OHSU mIHC images, then yes, I confirmed with Allison Creason at OHSU that these are indeed RGB, originally from SVS, and that they converted them to OME-TIFF and somehow screwed them up in the process. I am trying to convince them to submit SVS instead  so that they also remain compressed), or at least get the conversion right so that the OME-TIFF is RGB no three monochrome channels with no description.

**Comment by fedorov** [comment]
@hackermd I was using Chrome.

**Comment by hackermd** [comment]
Thanks for confirming @dclunie.

@fedorov I don't think there is anything we can (or should) about that from a viewer perspective.

**Comment by hackermd** [comment]
> @hackermd I was using Chrome.

Interesting! I was using Firefox, but could not reproduce this behavior in Chrome either.

Since this is a very unusual image, I think we can ignore the behavior.

**Comment by fedorov** [comment]
Sure, sounds good. 

I could not even quickly figure out how to open that same image to test if I can myself reproduce it, given the study/series UID pair.
